/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void insertTest() {
        LinkedList test1 = new LinkedList();
        test1.insert("dawood");
        String expected = "dawood";
        String actual = test1.head.value;
        assertEquals("insert dawood", expected, actual);
    }
    @Test
    public void includesTest(){
        LinkedList test3 = new LinkedList();
        test3.insert("dd");
        test3.insert("ss");
        test3.insert("ff");
        test3.insert("gg");
        test3.insert("ll");
        boolean box = test3.includes("dd");
        assertTrue(box, "should return dd");

    }

    @Test
    public void stringTest() {
        LinkedList test5 = new LinkedList();
        test5.insert("f");
        test5.insert("y");
        test5.insert("k");
        String expected = "{ k } -> { y } -> { f } -> NULL";
        String actual = test5.toString();
        assertEquals(expected, actual);
    }
    @Test
    public void appendTest(){
        LinkedList list = new LinkedList();
        list.insert("a");
        list.insert("b");
        list.insert("c");
        list.append("d");
        String expected = "{ c } -> { b } -> { a } -> { d } -> NULL";
        String actual = list.toString();
        assertEquals(expected, actual);
    }



    @Test
    public void insertBeforeTest(){
        LinkedList list = new LinkedList();
        list.insert("l");
        list.insert("e");
        list.insert("q");
        list.insertBefore("e", "b");
        String expected = "{ q } -> { b } -> { e } -> { l } -> NULL";
        String actual = list.toString();
        assertEquals(expected, actual);
    }

    @Test
    public void insertAfterTest(){
        LinkedList list = new LinkedList();
        list.insert("g");
        list.insert("h");
        list.insert("w");
        list.insertAfter("h", "i");
        String expected = "{ w } -> { 2 } -> { i } -> { g } -> NULL";
        String actual = list.toString();
        assertEquals(expected, actual);
    }

    @Test
    public void kthFromEndTest(){
        LinkedList list = new LinkedList();
        list.insert("i");
        list.insert("l");
        list.insert("o");
        list.insert("h");

        // test to see if the (k) is greater than the length of the linked list
        Object actual = list.kthFromEnd(5);
        Object expected = "Invalid value";
        assertEquals(" Tests that k is greater than the value", expected, (String) actual);

        // test to see if the (k) is the same length of the linked list
        Object actual1 = list.kthFromEnd(4);
        Object expected1 = "Invalid value";
        assertEquals(" Tests that k and value are the same length", expected1, (String) actual1);

    }

}
