/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.reverse;

public class App {
    public static String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int arrayRefVar[]={1, 2, 3, 4, 5, 6}; 
        arrayReverse(arrayRefVar);
        
     }
     public static void arrayReverse(int [] numbers)
     {
         int arrayRefVar[]=new int[numbers.length]; 
         int x=0;
         for(int i=numbers.length-1;i>=0;i--){
             arrayRefVar[x]=numbers[i];
             x++;
         }
         
         for(int i=0;i<=numbers.length-1;i++){
             numbers[i]=arrayRefVar[i];
             System.out.println(numbers[i]);
 
             
         }
        
     }
    

}
