/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {


    public static void main (String[] args) throws Exception {

        Stack<Integer> stackList = new Stack<>();
        stackList.push(2);
        stackList.push(1);
        stackList.push(8);
        stackList.push(10);
        System.out.println("ffffff");
        System.out.println(stackList.value);
    }
}