/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {


    public static void main (String[] args) throws Exception {

//        Stack<Integer> stackList = new Stack<>();
//        stackList.push(2);
//        stackList.push(1);
//        stackList.push(8);
//        stackList.push(10);
//        System.out.println("ffffff");
//        System.out.println(stackList.value);
//        System.out.println();
        Cat cat1=new Cat("Lolo");
        Cat cat2 =new Cat("smore");
        Dog dog=new Dog("rex");
        AnimalShelter test=new AnimalShelter();
        test.enqueue(cat1);
        test.enqueue(cat2);
        test.enqueue(dog);

        System.out.println(test.dequeue("cat") instanceof Dog);
    }

    public static boolean brackets(String br) {
        if (br.isEmpty()) return true;

        Stack<String> kStack = new Stack<>();
        String[] arrToCheck = br.split("");

        for (String value: arrToCheck) {
            if ((value.equals("}") || value.equals("]") || value.equals(")")) && kStack.isEmpty()) {
                return false;
            }
            if (value.equals("{") || value.equals("[") || value.equals("(")) {
                kStack.push(value);
            } else if (value.equals("}")) {
                if (kStack.top.value.equals("{")) kStack.pop();
                else return false;
            } else if (value.equals(")")) {
                if (kStack.top.value.equals("(")) kStack.pop();
                else return false;
            } else if (value.equals("]")) {
                if (kStack.top.value.equals("[")) kStack.pop();
                else return false;
            }
        }
        return kStack.isEmpty();
    }
}