/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import org.junit.jupiter.api.Test;

import java.util.EmptyStackException;

import static org.junit.jupiter.api.Assertions.*;
import static stack.and.queue.App.brackets;

class AppTest {

    @Test public void testPeek() {
        Stack<Object> newStack = new Stack<>();
        newStack.push(false);
        newStack.push(false);
        newStack.push(true);
        boolean expectedPeek = true;
        Object actualPeek = newStack.peek();
        assertEquals(expectedPeek, actualPeek, "Peeking should return the top value: true");
    }
    @Test public void testIsEmpty(){
        Stack<Object> newStack = new Stack<>();
        newStack.push(false);
        newStack.push("dog");
        newStack.push(25);
        newStack.pop();
        newStack.pop();
        newStack.pop();
        boolean expectedEmpty = true;
        Object actualEmpty = newStack.isEmpty();
        assertEquals(expectedEmpty, actualEmpty, "Should return true if empty");

    }
    @Test public void testExceptionOnEmpty(){
        Stack<Object> newStack = new Stack<>();
        newStack.push(false);
        newStack.push("dog");
        newStack.push(25);
        newStack.pop();
        newStack.pop();
        newStack.pop();
        assertThrows(EmptyStackException.class, newStack::pop);
    }

    @Test public void testCreateQueue(){
        Queue<Object> newQueue = new Queue<>();
        newQueue.enqueue(true);
        newQueue.enqueue("hello");
        newQueue.enqueue(50);
        boolean expected = true;
        Object actual = newQueue.peek();
        assertEquals(expected, actual, "Should return the first value queued: true");
    }
@Test public void testHappySenario()
{
    Cat cat1=new Cat("Lolo");
    Cat cat2 =new Cat("smore");
    Dog dog=new Dog("rex");
    AnimalShelter test=new AnimalShelter();
    test.enqueue(cat1);
    test.enqueue(cat2);
    test.enqueue(dog);


    System.out.println(test.dequeue("cat") instanceof Dog);
}


    @Test void stackQueueBrackets() {

        // If the String is empty return True -No brackets error-.
        String testString = "";
        assertTrue(brackets(testString));

        // If the String has no brackets -No brackets error-.
        testString = "dawood";
        assertTrue(brackets(testString));

        // If the brackets is true.
        testString = "dd ( c )";
        assertTrue(brackets(testString));

        // If the brackets is false.
        testString = " ( { d } ] a )";
        assertFalse(brackets(testString));

        // False Happy path.
        testString = "[ { ( { } ] )";
        assertFalse(brackets(testString));

        // True Happy path.
        testString = "[[({( )})]]";
        assertTrue(brackets(testString));

        // True Happy path.
        testString = "[[ Hi ]] ( wow )";
        assertTrue(brackets(testString));

    }


}
