/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");



    }

    @Test public void insertSortedArrayTester(){
        InsertSort insertSort = new InsertSort();
        ArrayList<Integer> newArray = new ArrayList<Integer>(Arrays.asList(8, 4, 23, 42, 16, 15));
        ArrayList actual = insertSort.insertSortArray(newArray);
        System.out.println(actual);
        ArrayList<Integer> expected = new ArrayList<Integer>(Arrays.asList(4, 8, 15, 16, 23, 42));

        assertArrayEquals(expected.toArray(), actual.toArray());

    }}
