/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array.reverse;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void appHasAArrayReverse() {
        App classUnderTest = new App();
        int arrayRefVar[]={1, 2, 3, 4, 5, 6}; 
        
        assertNotNull(classUnderTest.arrayReverse(arrayRefVar), "revesed array");
    }
}
