/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hashtable;

import org.junit.jupiter.api.Test;

import java.util.LinkedList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void hashtableBuilderTester(){
        Hashtable testTable = new Hashtable( 5);

        testTable.add(1, "first");
        testTable.add(2, "dog");
        testTable.add(3, "hello");
        testTable.add(0, "zero");
        testTable.add(1, "airplane");
        testTable.add(2, 4);

        LinkedList<Object> expected = new LinkedList<>();
        expected.add("dog");
        expected.add(4);
        LinkedList<Object> actual = testTable.get(2);
        assertEquals(expected, actual);

        LinkedList<Object> expected1 = new LinkedList<>();
        expected1.add("zero");
        LinkedList<Object> actual1 = testTable.get(0);
        assertEquals(expected1, actual1);

        assertTrue(testTable.contains(0));

        assertFalse(testTable.contains(4));



        int hashedTestKey = testTable.hash(90);
        assertTrue(hashedTestKey >= 0 && hashedTestKey <= 5);
        int hashedTestKey2 = testTable.hash("hello");
        assertTrue(hashedTestKey2 >= 0 && hashedTestKey2 <= 5);

        System.out.println(testTable.get(2));

    }
}
